from .continent_serializer import continentsSerializer
from .country_serializer import countrySerializer
from .organization_serializer import OrgnisationSerializer,OrgnisationSerializer1,OrgnisationSerializer2,OrganizationSerializer3
from .user_serializer import UserSerializer,LoginSerializer,ResendOtpSerializer,ResetSerializer,VerifySerializer,ResendOtpSerializer
from .state_serializers import StateSeerializer
from .district_serializer import DistrictSerializer
from .block_serializers import BlockSerializer
from .village_serializers import VillageSerializer