# Generated by Django 5.0.6 on 2024-06-25 07:52

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='continents',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_column='name', max_length=45)),
                ('alternativename', models.CharField(blank=True, db_column='alternativename', max_length=45, null=True)),
                ('desc', models.CharField(blank=True, db_column='desc', max_length=250, null=True)),
                ('type', models.CharField(choices=[('CONTINENT', 'CONTINENT')], db_column='type', default='CONTINENT', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('hindu_population', models.CharField(db_column='hindu_population', max_length=10000)),
                ('overall_population', models.CharField(db_column='overall_population', max_length=10000000)),
            ],
            options={
                'db_table': 'continent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_column='name', max_length=45)),
                ('capital', models.CharField(blank=True, db_column='capital', max_length=45, null=True)),
                ('alternativename', models.CharField(blank=True, db_column='alternativename', max_length=45, null=True)),
                ('desc', models.CharField(blank=True, db_column='desc', max_length=250, null=True)),
                ('type', models.CharField(blank=True, choices=[('COUNTRY', 'COUNTRY')], db_column='type', default='COUNTRY', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_location', models.TextField(db_column='image_location')),
                ('hindu_population', models.CharField(db_column='hindu_population', max_length=10000)),
                ('overall_population', models.CharField(db_column='overall_population', max_length=10000000)),
            ],
            options={
                'db_table': 'country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='organization',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('organization_name', models.CharField(max_length=200, validators=[django.core.validators.MaxLengthValidator(200), django.core.validators.MinLengthValidator(2, 'Organization name cannot be empty')])),
                ('est_by', models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100), django.core.validators.MinLengthValidator(1, 'Establisher name cannot be empty')])),
                ('chairman', models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100), django.core.validators.MinLengthValidator(1, 'Chairman name cannot be empty')])),
                ('desc', models.TextField(validators=[django.core.validators.MinLengthValidator(1, 'Description cannot be empty')])),
                ('est_date', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50), django.core.validators.MinLengthValidator(1, 'Establishment date cannot be empty'), django.core.validators.RegexValidator(message='Date must be in YYYY-MM-DD format')])),
                ('reg_id', models.CharField(max_length=200, validators=[django.core.validators.MaxLengthValidator(200), django.core.validators.MinLengthValidator(1, 'Registration ID cannot be empty')])),
                ('location', models.TextField(validators=[django.core.validators.MinLengthValidator(1, 'Location cannot be empty')])),
                ('web_url', models.URLField(validators=[django.core.validators.URLValidator(message='Invalid URL format')])),
                ('org_detail', models.CharField(max_length=200, validators=[django.core.validators.MaxLengthValidator(200), django.core.validators.MinLengthValidator(1, 'Organization detail cannot be empty')])),
                ('mission', models.TextField(validators=[django.core.validators.MinLengthValidator(1, 'Mission cannot be empty')])),
                ('org_images', models.TextField(validators=[django.core.validators.MinLengthValidator(1, 'Organization images cannot be empty')])),
                ('org_logo', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('INACTIVE', 'INACTIVE')], default='PENDING', max_length=50)),
            ],
            options={
                'db_table': 'organization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(db_column='first_name', max_length=200)),
                ('last_name', models.CharField(db_column='last_name', max_length=200)),
                ('dob', models.DateField()),
                ('verification_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('verification_otp_created_time', models.DateTimeField(null=True)),
                ('verification_otp_resend_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='CREATED', max_length=50)),
                ('forgot_password_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('forgot_password_otp_created_time', models.DateTimeField(null=True)),
                ('forgot_password_otp_resend_count', models.IntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'profile',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
