# Generated by Django 5.0.6 on 2024-05-24 10:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_column='name', max_length=45)),
                ('capital', models.CharField(blank=True, db_column='capital', max_length=45, null=True)),
                ('alternativename', models.CharField(blank=True, db_column='alternativename', max_length=45, null=True)),
                ('desc', models.CharField(blank=True, db_column='desc', max_length=250, null=True)),
                ('type', models.CharField(blank=True, choices=[('COUNTRY', 'COUNTRY')], db_column='type', default='COUNTRY', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='organization',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('organization_name', models.CharField(max_length=200)),
                ('est_by', models.CharField(max_length=100)),
                ('chairman', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('est_date', models.CharField(max_length=200)),
                ('reg_id', models.CharField(max_length=200)),
                ('location', models.TextField()),
                ('wed_url', models.URLField()),
                ('org_detail', models.CharField(max_length=200)),
                ('mission', models.TextField()),
                ('org_images', models.TextField()),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country', to='hindu.country')),
            ],
            options={
                'db_table': 'organization',
            },
        ),
    ]
