# Generated by Django 5.0.6 on 2024-08-26 05:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hindu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('desc', models.TextField(db_column='desc', null=True)),
            ],
            options={
                'db_table': 'article_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleSubCategory',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('desc', models.CharField(db_column='desc', max_length=5000)),
            ],
            options={
                'db_table': 'article_sub_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('article', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS')], db_column='status', default='PENDING', max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('category_id', models.ForeignKey(db_column='category_id', max_length=45, null=True, on_delete=django.db.models.deletion.CASCADE, to='hindu.category')),
                ('subcategory_id', models.ForeignKey(db_column='sub_category', max_length=45, null=True, on_delete=django.db.models.deletion.CASCADE, to='hindu.subcategory')),
            ],
            options={
                'db_table': 'article',
                'ordering': ['-created_at'],
            },
        ),
    ]
