# Generated by Django 5.0.6 on 2024-05-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hindu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='chairman',
            field=models.CharField(db_column='chairman', max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='desc',
            field=models.TextField(db_column='desc'),
        ),
    ]
