# Generated by Django 5.0.6 on 2024-07-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hindu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
