# Generated by Django 5.0.6 on 2024-07-23 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hindu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subcategory',
            table='sub_category',
        ),
    ]
