# Generated by Django 5.0.6 on 2024-09-21 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hindu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingsubcategory',
            options={'managed': False},
        ),
    ]
