# Generated by Django 5.0.6 on 2024-07-10 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hindu', '0002_register_is_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='is_email_verified',
        ),
    ]
