# Generated by Django 5.0.6 on 2024-06-13 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hindu', '0002_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='gotram',
        ),
    ]
