# Generated by Django 5.0.6 on 2024-07-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hindu', '0003_remove_register_is_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='village',
            name='block',
        ),
        migrations.AddField(
            model_name='district',
            name='image_location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='Block',
        ),
        migrations.DeleteModel(
            name='Village',
        ),
    ]
